services:
  - type: web
    name: hotelback
    runtime: docker
    plan: free
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_TOKEN
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: JWT_REFRESH_EXPIRATION
        value: "604800000"
