spring.application.name=hotelback
spring.profiles.default=dev

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${SERVER_PORT:8082}

jwt.expiration=${JWT_EXPIRATION:86400000}
